categories:
  - title: "Features"
    label: "feature"
  - title: "Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "Chores"
    labels:
      - "chore"
      - "dependencies"
template: |
  $CHANGES
