# Welcome to Mago!
# For full documentation, see https://mago.carthage.software/tools/overview
php-version = "8.4.0"

[source]
paths = [
    "src",
    "tests",
    "workbench/app/",
    "workbench/database/factories/",
    "workbench/database/seeders/",
]
includes = ["vendor"]
excludes = []

[formatter]
print-width = 120
tab-width = 4
use-tabs = false
null-type-hint = "question"

[linter]
integrations = ["laravel"]

[linter.rules]
ambiguous-function-call = { enabled = false }
literal-named-argument = { enabled = false }
halstead = { effort-threshold = 7000 }
return-type = { ignore-arrow-function = true }
constant-type = { enabled = false }
class-name = { enabled = false }
interface-name = { enabled = false }

[analyzer]
excludes = ['tests']


# Analyzer Settings
find-unused-definitions = true
find-unused-expressions = false
analyze-dead-code = false
check-throws = false
allow-possibly-undefined-array-keys = true
perform-heuristic-checks = true
