[source]
paths = ["src", "tests"]
includes = ["vendor"]

[format]
null_type_hint = "question"

[linter]
default_plugins = true
plugins = ["laravel"]

[[linter.rules]]
name = "strictness/require-return-type"
ignore_arrow_function = true

[[linter.rules]]
name = "analysis/undefined-function-or-method"
allow_dynamic_static_calls = true
level = "off"

[[linter.rules]]
name = "best-practices/override-attribute"
level = "off"

[[linter.rules]]
name = "naming/class"
level = "off"

[[linter.rules]]
name = "best-practices/literal-named-argument"
level = "off"

[[linter.rules]]
name = "naming/interface"
level = "off"

[[linter.rules]]
# since we support php 8.2 we cannot use constant types
name = "strictness/require-constant-type"
level = "off"
