[source]
paths = ["src", "tests"]
includes = ["vendor"]

[format]
method_chain_break_threshold = 2
null_type_hint = "question"

[[linter.rules]]
name = "strictness/require-return-type"
ignore_arrow_function = true
