[source]
paths = ["src", "tests"]
includes = ["vendor"]

[format]
method_chain_break_threshold = 2
null_type_hint = "question"

[[linter.rules]]
name = "strictness/require-return-type"
ignore_arrow_function = true

[[linter.rules]]
name = "analysis/undefined-function-or-method"
allow_dynamic_static_calls = true
level = "off"

[[linter.rules]]
name = "analysis/override-attribute"
level = "off"

[[linter.rules]]
name = "naming/class"
level = "off"

[[linter.rules]]
name = "naming/interface"
level = "off"

