name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: php-actions/composer@v6
        with:
          php_extensions: zip

      - name: Install dependencies
        run: npm ci

      - name: Compile assets
        run: npm run build

      - name: Create zip
        run: cd resources && tar -czvf dist.tar.gz dist

      - name: Generate release notes
        uses: orhun/git-cliff-action@v4
        id: generate_release_notes
        with:
          args: -v --latest --strip header -c git-cliff-config.toml --gitup-repo "itiden/statamic-backup"

      - name: Clean up release notes
        run: |
          cat ${{ steps.generate_release_notes.outputs.changelog }}
          cat ${{ steps.generate_release_notes.outputs.changelog }} | sed '1,2d' > release_notes.txt

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: release_notes.txt
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - name: Upload zip to release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./resources/dist.tar.gz
          asset_name: dist.tar.gz
          asset_content_type: application/tar+gz
